
download.file("https://raw.githubusercontent.com/markziemann/SLE712_files/master/bioinfo_asst3_part1_files/mydata.tsv",
              destfile = "mydata.tsv")
x <- read.table("mydata.tsv")
head(x)
str(x)
x <- read.table("mydata.tsv",header=TRUE)
head(x)
str(x)
x <- read.table("mydata.tsv", header = TRUE, row.names = 1)
head(x)
str(x)
x <- read.table("mydata.tsv", header = TRUE , stringsAsFactors = FALSE )
head(x)
str(x)
x <- read.csv("mydata.tsv", sep="\t")
head(x)
str(x)
x <- read.csv("mydata.tsv", sep="\t",stringsAsFactors = FALSE)
head(x)